# Generated by Django 5.1.4 on 2025-01-01 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('emergency', 'Приемное отделение'), ('cardiology', 'Кардиология'), ('neurology', 'Неврология'), ('surgery', 'Хирургия'), ('pediatrics', 'Педиатрия'), ('oncology', 'Онкология'), ('gynecology', 'Гинекология'), ('urology', 'Урология'), ('orthopedics', 'Ортопедия'), ('dermatology', 'Дерматология'), ('radiology', 'Радиология'), ('anesthesiology', 'Анестезиология'), ('gastroenterology', 'Гастроэнтерология'), ('pulmonology', 'Пульмонология'), ('hematology', 'Гематология'), ('psychiatry', 'Психиатрия'), ('rehabilitation', 'Реабилитация')], max_length=60)),
                ('location', models.CharField(max_length=250)),
                ('chief_physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_app.doctorprofile', verbose_name='главный врач')),
            ],
        ),
    ]
