# Generated by Django 5.1.4 on 2025-01-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hospital', '0002_appointment_billings_feedback_medicalrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ward_type', models.CharField(choices=[('VIP', 'VIP'), ('STANDARD', 'STANDARD')], default='STANDARD', max_length=12)),
                ('capacity', models.PositiveIntegerField(default=5)),
                ('current_capacity', models.PositiveIntegerField()),
            ],
        ),
    ]
