# Generated by Django 5.1.4 on 2025-01-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hospital', '0003_wards'),
        ('profile_app', '0003_alter_doctorprofile_working_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wards',
            name='current_capacity',
        ),
        migrations.AddField(
            model_name='wards',
            name='patients',
            field=models.ManyToManyField(to='profile_app.patientprofile'),
        ),
    ]
