# Generated by Django 5.1.4 on 2025-01-05 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hospital', '0005_category_direction_and_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction_and_services',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.RemoveField(
            model_name='direction_and_services',
            name='description',
        ),
        migrations.CreateModel(
            name='Name_Direction_and_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_name', to='my_hospital.direction_and_services')),
            ],
        ),
        migrations.DeleteModel(
            name='Category_Direction_and_Services',
        ),
    ]
