# Generated by Django 5.1.4 on 2025-01-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hospital', '0006_alter_direction_and_services_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name_direction_and_services',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
