# Generated by Django 5.1.4 on 2025-01-05 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hospital', '0008_procedurename_pricelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelist',
            name='procedure',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='procedure_name',
        ),
        migrations.RemoveField(
            model_name='procedurename',
            name='name',
        ),
        migrations.AddField(
            model_name='pricelist',
            name='name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedurename',
            name='procedure',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedurename',
            name='procedure_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='procedure_name', to='my_hospital.pricelist'),
            preserve_default=False,
        ),
    ]
