# Generated by Django 5.1.4 on 2025-01-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hospital', '0009_remove_pricelist_procedure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedurename',
            name='price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
