# Generated by Django 5.1.4 on 2025-01-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hospital', '0011_direction_and_services_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction_and_services',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
