# Generated by Django 5.1.4 on 2025-01-05 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hospital', '0012_direction_and_services_description'),
        ('profile_app', '0003_alter_doctorprofile_working_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction_and_services',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Specialists', to='profile_app.doctorprofile'),
        ),
    ]
