# Generated by Django 5.1.4 on 2025-01-05 12:48

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hospital', '0014_remove_direction_and_services_doctor_and_more'),
        ('profile_app', '0003_alter_doctorprofile_working_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=32, unique=True)),
                ('hospital_image', models.ImageField(upload_to='hospital_image/')),
                ('address', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('operating_mode', models.CharField(max_length=300)),
                ('chief_physician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profile_app.doctorprofile', verbose_name='Главный врач')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KG')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_hospital.hospitalprofile')),
            ],
        ),
    ]
