# Generated by Django 5.1.4 on 2025-01-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hospital', '0015_hospitalprofile_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='location_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='location_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='name_en',
            field=models.CharField(choices=[('emergency', 'Приемное отделение'), ('cardiology', 'Кардиология'), ('neurology', 'Неврология'), ('surgery', 'Хирургия'), ('pediatrics', 'Педиатрия'), ('oncology', 'Онкология'), ('gynecology', 'Гинекология'), ('urology', 'Урология'), ('orthopedics', 'Ортопедия'), ('dermatology', 'Дерматология'), ('radiology', 'Радиология'), ('anesthesiology', 'Анестезиология'), ('gastroenterology', 'Гастроэнтерология'), ('pulmonology', 'Пульмонология'), ('hematology', 'Гематология'), ('psychiatry', 'Психиатрия'), ('rehabilitation', 'Реабилитация')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='name_ru',
            field=models.CharField(choices=[('emergency', 'Приемное отделение'), ('cardiology', 'Кардиология'), ('neurology', 'Неврология'), ('surgery', 'Хирургия'), ('pediatrics', 'Педиатрия'), ('oncology', 'Онкология'), ('gynecology', 'Гинекология'), ('urology', 'Урология'), ('orthopedics', 'Ортопедия'), ('dermatology', 'Дерматология'), ('radiology', 'Радиология'), ('anesthesiology', 'Анестезиология'), ('gastroenterology', 'Гастроэнтерология'), ('pulmonology', 'Пульмонология'), ('hematology', 'Гематология'), ('psychiatry', 'Психиатрия'), ('rehabilitation', 'Реабилитация')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='address_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='address_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='hospital_name_en',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='hospital_name_ru',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='operating_mode_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='operating_mode_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='diagnosis_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='diagnosis_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='prescribed_medication_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='prescribed_medication_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosage_en',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosage_ru',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medication_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medication_ru',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
