# Generated by Django 5.1.4 on 2025-01-06 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_hospital', '0016_departments_location_en_departments_location_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name_direction_and_services',
            old_name='name',
            new_name='direction',
        ),
    ]
