# Generated by Django 5.1.4 on 2025-01-06 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hospital', '0017_rename_name_name_direction_and_services_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction_and_services',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='direction_and_services',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='direction_and_services',
            name='name_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='direction_and_services',
            name='name_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='name_direction_and_services',
            name='description_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='name_direction_and_services',
            name='description_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='name_direction_and_services',
            name='direction_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_name', to='my_hospital.direction_and_services'),
        ),
        migrations.AddField(
            model_name='name_direction_and_services',
            name='direction_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_name', to='my_hospital.direction_and_services'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='name_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='name_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='procedurename',
            name='procedure_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='procedurename',
            name='procedure_ru',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
