# Generated by Django 5.1.4 on 2025-01-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_hospital', '0018_direction_and_services_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name_direction_and_services',
            name='direction_en',
        ),
        migrations.RemoveField(
            model_name='name_direction_and_services',
            name='direction_ru',
        ),
    ]
