# Generated by Django 5.1.4 on 2025-01-01 16:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KG')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('specialty', models.CharField(choices=[('cardiologist', 'Кардиолог'), ('dentist', 'Стоматолог'), ('neurologist', 'Невролог'), ('pediatrician', 'Педиатр'), ('surgeon', 'Хирург'), ('psychiatrist', 'Психиатр'), ('dermatologist', 'Дерматолог'), ('oncologist', 'Онколог'), ('gynecologist', 'Гинеколог'), ('urologist', 'Уролог'), ('orthopedist', 'Ортопед'), ('ophthalmologist', 'Офтальмолог'), ('endocrinologist', 'Эндокринолог'), ('immunologist', 'Иммунолог'), ('hematologist', 'Гематолог'), ('anesthesiologist', 'Анестезиолог'), ('radiologist', 'Рентгенолог'), ('pulmonologist', 'Пульмонолог'), ('gastroenterologist', 'Гастроэнтеролог'), ('rheumatologist', 'Ревматолог'), ('nephrologist', 'Нефролог'), ('nurse', 'Медсестра'), ('paramedic', 'Фельдшер'), ('general_practitioner', 'Врач общей практики')], max_length=30)),
                ('department', models.CharField(choices=[('emergency', 'Приемное отделение'), ('cardiology', 'Кардиология'), ('neurology', 'Неврология'), ('surgery', 'Хирургия'), ('pediatrics', 'Педиатрия'), ('oncology', 'Онкология'), ('gynecology', 'Гинекология'), ('urology', 'Урология'), ('orthopedics', 'Ортопедия'), ('dermatology', 'Дерматология'), ('radiology', 'Радиология'), ('anesthesiology', 'Анестезиология'), ('gastroenterology', 'Гастроэнтерология'), ('pulmonology', 'Пульмонология'), ('hematology', 'Гематология'), ('psychiatry', 'Психиатрия'), ('rehabilitation', 'Реабилитация')], max_length=30)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('working_days', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], max_length=20)),
                ('role', models.CharField(choices=[('doctor', 'doctor')], default='doctor', max_length=15)),
                ('price', models.PositiveIntegerField(default=200)),
                ('experience_year', models.PositiveIntegerField(default=1)),
                ('qualification', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('profile_app.profile',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('blood_type', models.CharField(choices=[('A+', 'Группа крови A (положительная)'), ('A-', 'Группа крови A (отрицательная)'), ('B+', 'Группа крови B (положительная)'), ('B-', 'Группа крови B (отрицательная)'), ('AB+', 'Группа крови AB (положительная)'), ('AB-', 'Группа крови AB (отрицательная)'), ('O+', 'Группа крови O (положительная)'), ('O-', 'Группа крови O (отрицательная)')], max_length=50)),
                ('date_of_birth', models.DateField()),
                ('role', models.CharField(choices=[('patient', 'patient')], default='patient', max_length=15)),
                ('allergies', models.TextField()),
                ('medical_history', models.TextField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('profile_app.profile',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
