# Generated by Django 5.1.4 on 2025-01-01 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctors_Profile'},
        ),
        migrations.AlterModelOptions(
            name='patientprofile',
            options={'verbose_name': 'Patient', 'verbose_name_plural': 'Patients_Profile'},
        ),
    ]
