# Generated by Django 5.1.4 on 2025-01-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_alter_doctorprofile_working_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='shift_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='shift_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
